.gitignore
contracts/exchange/api/AccountContract.sol
contracts/exchange/api/TradeContract.sol
package.json

This PR fix a arithmetic deviation from the risk's implementation

fix fuzz tests

---

contracts/exchange/api/BaseContract.sol
hardhat.config.ts
package.json

Proposed solution to https://github.com/gravity-technologies/exchange-contract/pull/140#issuecomment-2241338069

Use immutable variable to store domain typehash

---

contracts/exchange/api/BaseContract.sol
deploy/setexchangeaddr.ts
hardhat.config.ts
package.json
test/util.ts

TODO: wait for https://github.com/gravity-technologies/platform/pull/5105 to be merged and regenerate RTF tests

Add a compile time replacement for chainID.

---

contracts/exchange/api/signature/generated/OracleSig.sol
contracts/exchange/api/signature/generated/TradeSig.sol

spearbit-20: optimise gas usage for hashing oracle/trade/liquidation payload

---

contracts/exchange/api/AccountContract.sol

spearbit-64: remove redundant accountID check

---

contracts/exchange/common/Error.sol
contracts/exchange/types/DataStructure.sol

spearbit-65: remove unused construct

---

contracts/exchange/api/OracleContract.sol

spearbit-55: remove incorrect comment in funding tick api

---

contracts/exchange/GRVTExchange.sol
contracts/exchange/GRVTExchangeTest.sol

spearbit-67: add missing call to disableInitialiser

---

contracts/exchange/api/TradeContract.sol

spearbit-15: add more order validations in trade

---

contracts/exchange/api/TradeContract.sol
contracts/exchange/types/DataStructure.sol

spearbit-14 spearbit-16: add matched order validation

---

contracts/exchange/api/RiskCheck.sol

spearbit-21: Incorrect maintenance margin tier selection may lead to incorrect margin requirements and potential liquidations

---

contracts/exchange/api/RiskCheck.sol

spearbit-35: check margin type in isAboveMaintenanceMargin

---

contracts/exchange/api/TradeContract.sol

spearbit-17: validate postOnly and reduceOnly order

---

contracts/exchange/api/TradeContract.sol
contracts/exchange/types/DataStructure.sol

spearbit-34: verify asset expiry

---

contracts/exchange/api/BaseContract.sol

spearbit-47: make get balance decimals more explicit

---

contracts/exchange/api/OracleContract.sol

Allow txID gap for markPriceTick to support mark price compression.

Allow txID gap for mark price tick

---

contracts/exchange/api/AssertionContract.sol

- Add last tx ID assertion
- Add initialize config assertion

Assertion fixes

---

contracts/exchange/api/TradeContract.sol

Stacked PRs:
* #222
* __->__#221
--- --- ---

Refactor tradeDeriv

---

contracts/DepositProxy.sol
contracts/exchange/GRVTExchange.sol
contracts/exchange/GRVTExchangeTest.sol
contracts/exchange/api/AccountContract.sol
contracts/exchange/api/BaseContract.sol
contracts/exchange/api/TransferContract.sol
contracts/exchange/types/DataStructure.sol
hardhat.config.ts
scripts/deploy-exchange-on-l2-through-l1.ts
test/engine/RTFEngine.test.ts
test/engine/deposit.ts
test/engine/runner.ts
test/engine/setup.ts
test/engine/types.ts
test/foundry/Base.t.sol

Stacked PRs:
* __->__#222
--- --- ---

Implement DepositProxy logic

---

contracts/exchange/GRVTExchangeTest.sol
contracts/exchange/api/AssertionContract.sol
contracts/exchange/api/ConfigContract.sol
contracts/exchange/api/MarginConfigContract.sol
contracts/exchange/api/RiskCheck.sol
contracts/exchange/types/DataStructure.sol

This PR adds gaps to all structs that are in storage. With gaps we can freely upgrade these in the future

add gaps in storage struct to allow future upgrade

---

contracts/exchange/api/BaseContract.sol
contracts/exchange/api/FundingAndSettlement.sol
contracts/exchange/api/MarginConfigContract.sol
contracts/exchange/api/RiskCheck.sol
contracts/exchange/api/TransferContract.sol
contracts/exchange/util/BIMath.sol
test/engine/expect.ts
test/engine/types.ts
test/foundry/util/BIMath.t.sol

- Align funding payment
- Fix exchange balance expectation

Fix funding payment amount calculation

---

contracts/exchange/api/RiskCheck.sol

Reverts gravity-technologies/exchange-contract#270

Revert "Temporarily remove KAITO MM requirement"
